apiVersion: apps/v1
kind: Deployment
metadata:
  name:
  labels:
    app:
spec:
  replicas: 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - name:
        image:
        ports:
        - containerPort:
