apiVersion: v1
Kind: Service
metadata:
  name:{{.values.service.name}}
spec:
  type:{{.values.service.type}}
  selector: 
  app: {{.values.service.label}}
 ports:
   - port: {{.values.service.port}}
     targetport : {{.values.service.port}}
      nodeport: {{.values.service.port}}
